### PR TITLE
s390x: allow lifting of vector instructions

### PR DESCRIPTION
**Pull request by mephi42**
guest_s390_toIR lifts vector instructions only if host supports them,
which is never going to happen when using it on x86, so let's fool the
check.

Additionally, in context of rebasing discussion, I thought it would
make sense to make hacks like this stand out. So I wrapped it in PYVEX
ifdef.

### CODE REVIEW

**Comment by twizmwazin** [comment]
@rhelmot Unless someone else takes it on, I'm probably not going to get around to the whole rebase thing for a while, at least until after CI stuff. In the interest of not blocking on something without a concrete timeline, do we want to merge this and #25?

**Comment by rhelmot** [comment]
Yes, we should merge these.

**Comment by mephi42** [comment]
I've just realized that I accidentally undind 87028799cd56 ("s390x: handle EXRL when its target is in the same buffer") - I've just pushed a fix for this.

**Comment by rhelmot** [comment]
I think generally anything that happens in toir instead of isel that depends on the host configuration instead of the guest configuration should be considered a bug. Feel free to change that - I'm ok with this but would prefer the cleaner approach.

@twizmwazin, reminder that this is assigned to you.

**Comment by mephi42** [comment]
Actually, in the meantime all the host endianness checks have been removed.

What remains are various feature checks (presence of decimal floating point, vectors, etc), but, well, that's how upstream developers wanted it to be. For now I added a workaround to pretend the host has some of these features (maybe I'll need to add more in the future? for binaries I'm looking at only two were necessary).

I will ask the maintainers what they think about moving feature checks to isel, but that might be a bit harder to get through than host endianness changes.

**Comment by rhelmot** [comment]
btw @mephi42, I noticed that one of the s390 tests in pyvex was failing: https://dev.azure.com/angr/pyvex/_build/results?buildId=1506&view=ms.vss-test-web.build-test-results-tab&runId=24146&resultId=100082&paneView=debug

**Comment by mephi42** [comment]
Thanks for merging this!

You also need https://github.com/angr/pyvex/pull/186 - it fixes the test and adds a couple new ones,

**Pull request merged**
