### PR TITLE
VEX IR generator added for RISCV WFI instruction

### PR DESCRIPTION
**Pull request by EvelynVusky**
Added a VEX IR generator for the RISC-V WFI instruction in the dis_RV64Zicsr() function of guest_riscv64_toIR.c.

### CODE REVIEW

**Review by rhelmot — APPROVED** [review]

**Comment by rhelmot** [comment]
I have absolutely no ability to review riscv-related code, so I will instead ask you this:

- does it work in your tests?
- is it ready to merge?

**Comment by EvelynVusky** [comment]
@rhelmot Yes, the VEX IR generator for the RISCV WFI instruction works and we believe it is ready to merge.

**Comment by rhelmot** [comment]
I'm only asking this because you added a commit to this branch related to CSR operations. Are those supposed to be merged now too?

**Comment by EvelynVusky** [comment]
@rhelmot No. We would like to submit the second commit related to CSR operations as a separate pull request, but we've got some more testing to do before submitting it. 

Is it possible to merge just the initial commit ("VEX IR generator added for RISCV WFI instruction")? If not, we can back the second CSR commit out of the branch.

**Comment by rhelmot** [comment]
No, pull requests on github track branches, and I don't have the option to merge just some commits of a pull request. You'll need to either revert or reset that commit.

**Comment by EvelynVusky** [comment]
@rhelmot Understood, thank you. Just reverted the commit.

**Comment by rhelmot** [comment]
Thanks!

**Pull request merged**
